### ISSUE TITLE
Node does not compile on first run Ubuntu 18.04 

### ISSUE THREAD

**Issue by maledon** [koush/support-wiki#186]
Although read me says node will compile on 1st run, instead it asks user to compile, but then 18.04 will always take user to:

Downloads/Tether/node$ ./configure
Traceback (most recent call last):
  File "./configure", line 463, in <module>
    configure_node(output)
  File "./configure", line 370, in configure_node
    o['variables']['gcc_version'] = 10 * cc_version[0] + cc_version[1]
IndexError: tuple index out of range

**Comment by maledon** [comment]
changing     dumpversion to  dumpfullversion in line 325 of ./configure will get it to configure, but then when you make it, you will get this error:
In file included from ../deps/v8/src/elements.h:32:0,
                 from ../deps/v8/src/objects-inl.h:38,
                 from ../deps/v8/src/v8.h:60,
                 from ../deps/v8/src/accessors.cc:28:
../deps/v8/src/objects.h: At global scope:
../deps/v8/src/objects.h:5017:44: error: left operand of shift expression ‘(-1 << 3)’ is negative [-fpermissive]
   static const int kElementsKindMask = (-1 << kElementsKindShift) &
                                        ~~~~^~~~~~~~~~~~~~~~~~~~~~
../deps/v8/src/objects.h:7152:36: error: left operand of shift expression ‘(-8 << 26)’ is negative [-fpermissive]
       (~kMaxCachedArrayIndexLength << kArrayIndexHashLengthShift) |
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
deps/v8/tools/gyp/v8_base.target.mk:211: recipe for target '/home/elickm/Downloads/1tether/tether-linux/Tether/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o' failed
make[1]: *** [/home/elickm/Downloads/1tether/tether-linux/Tether/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o] Error 1
make[1]: Leaving directory '/home/elickm/Downloads/1tether/tether-linux/Tether/node/out'
Makefile:26: recipe for target 'node' failed
make: *** [node] Error 2

**Comment by leftdisconnected** [comment]
Same sort of error on MX 17.1, so I believe this problem persists across multiple distros (MX 17 is based on Debian 9).

Here's the end portion of the compile output:

...
/home/demo/Desktop/Tether/node/out/Release/obj.target/uv/deps/uv/src/unix/linux/syscalls.o
  LD_LIBRARY_PATH=/home/demo/Desktop/Tether/node/out/Release/lib.host:/home/demo/Desktop/Tether/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8/tools/gyp; mkdir -p /home/demo/Desktop/Tether/node/out/Release/obj/gen; python ../../tools/js2c.py "/home/demo/Desktop/Tether/node/out/Release/obj/gen/libraries.cc" CORE off ../../src/runtime.js ../../src/v8natives.js ../../src/array.js ../../src/string.js ../../src/uri.js ../../src/math.js ../../src/messages.js ../../src/apinatives.js ../../src/debug-debugger.js ../../src/mirror-debugger.js ../../src/liveedit-debugger.js ../../src/date.js ../../src/json.js ../../src/regexp.js ../../src/macros.py
  LD_LIBRARY_PATH=/home/demo/Desktop/Tether/node/out/Release/lib.host:/home/demo/Desktop/Tether/node/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8/tools/gyp; mkdir -p /home/demo/Desktop/Tether/node/out/Release/obj/gen; python ../../tools/js2c.py "/home/demo/Desktop/Tether/node/out/Release/obj/gen/experimental-libraries.cc" EXPERIMENTAL off ../../src/macros.py ../../src/proxy.js ../../src/collection.js
  touch /home/demo/Desktop/Tether/node/out/Release/obj.target/deps/v8/tools/gyp/js2c.stamp
  g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DENABLE_DEBUGGER_SUPPORT' '-DV8_TARGET_ARCH_X64' -I../deps/v8/src  -Wall -pthread -m64 -fno-strict-aliasing -O2 -fno-strict-aliasing -fno-tree-vrp -fno-rtti -fno-exceptions -MMD -MF /home/demo/Desktop/Tether/node/out/Release/.deps//home/demo/Desktop/Tether/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o.d.raw  -c -o /home/demo/Desktop/Tether/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o ../deps/v8/src/accessors.cc
In file included from ../deps/v8/src/v8globals.h:32:0,
                 from ../deps/v8/src/v8.h:53,
                 from ../deps/v8/src/accessors.cc:28:
../deps/v8/src/v8utils.h: In function ‘void v8::internal::CopyWords(T*, T*, int)’:
../deps/v8/src/checks.h:251:22: warning: typedef ‘__StaticAssertTypedef__125’ locally defined but not used [-Wunused-local-typedefs]
     SEMI_STATIC_JOIN(__StaticAssertTypedef__, __LINE__)
                      ^
../deps/v8/src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../deps/v8/src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(__StaticAssertTypedef__, __LINE__)
     ^~~~~~~~~~~~~~~~
../deps/v8/src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^~~~~~~~~~~~
../deps/v8/src/v8utils.h:125:3: note: in expansion of macro ‘STATIC_ASSERT’
   STATIC_ASSERT(sizeof(T) == kPointerSize);
   ^~~~~~~~~~~~~
In file included from ../deps/v8/src/elements.h:32:0,
                 from ../deps/v8/src/objects-inl.h:38,
                 from ../deps/v8/src/v8.h:60,
                 from ../deps/v8/src/accessors.cc:28:
../deps/v8/src/objects.h: At global scope:
../deps/v8/src/objects.h:5017:44: error: left operand of shift expression ‘(-1 << 3)’ is negative [-fpermissive]
   static const int kElementsKindMask = (-1 << kElementsKindShift) &
                                        ~~~~^~~~~~~~~~~~~~~~~~~~~~
../deps/v8/src/objects.h:7152:36: error: left operand of shift expression ‘(-8 << 26)’ is negative [-fpermissive]
       (~kMaxCachedArrayIndexLength << kArrayIndexHashLengthShift) |
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
deps/v8/tools/gyp/v8_base.target.mk:209: recipe for target '/home/demo/Desktop/Tether/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o' failed
make[1]: *** [/home/demo/Desktop/Tether/node/out/Release/obj.target/v8_base/deps/v8/src/accessors.o] Error 1
make[1]: Leaving directory '/home/demo/Desktop/Tether/node/out'
Makefile:26: recipe for target 'node' failed
make: *** [node] Error 2

**Comment by shach33** [comment]
Hi, 

I am still having this same issue. Could you find any solution for this?

**Comment by leftdisconnected** [comment]
I certainly didn't.  I gave up and stopped using Tether.  I haven't found a way to use a 3rd-party tethering app from Linux, though I'm sure that it's possible to do so.  

There have been no issues closed since December, so I don't expect that this will be resolved.  I wish koush all the best, however.

**Comment by shach33** [comment]
I used the latest version of nodejs from https://github.com/nodejs/node and did not face this anymore.

**Comment by leftdisconnected** [comment]
Thanks for the update!
